In [2]:
import numpy as np

In [3]:
myArray = np.array([1,2,3,4,5,6])
myList = [1,2,3,4,5,6]

In [4]:
myArray

array([1, 2, 3, 4, 5, 6])

In [5]:
multylyList = myList * 5
multyplyArray = myArray / 5
print (multylyList,multyplyArray)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6] [0.2 0.4 0.6 0.8 1.  1.2]


In [6]:
Arraytambah = myArray + 5
Arraykurang = myArray - 5
Arraybagi = myArray / 5
Arraykali = myArray * 5

In [7]:
Listtambah = myList + 5
Listkurang = myList - 5
Listbagi = myList / 5
Listkali = myList * 5

TypeError: can only concatenate list (not "int") to list

In [8]:
print(Arraybagi,Arraykali,Arraykurang,Arraytambah)

[0.2 0.4 0.6 0.8 1.  1.2] [ 5 10 15 20 25 30] [-4 -3 -2 -1  0  1] [ 6  7  8  9 10 11]


In [9]:
mybool = myArray > 3
mybool

array([False, False, False,  True,  True,  True])

In [10]:
array3x4 = np.array(([1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]))
array3x4
print(array3x4.shape) #ukuran array
print(type(array3x4))


(3, 4)
<class 'numpy.ndarray'>


In [11]:
print(array3x4[0: ,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [12]:
first = array3x4[0:]
kedua = array3x4[0:3]
print(first)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(kedua)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
data = np.genfromtxt("./data.csv" , skip_header=1 ,delimiter=",",filling_values=40)
data

array([[70., 70., 24., 24.],
       [90., 80., 68., 46.],
       [12., 35., 45., 78.],
       [12., 34., 56., 67.]])

In [15]:
max = np.amax(data,axis=0)
max1 = np.amax(data,axis=1)
print(max)
print(max1)

[90. 80. 68. 78.]
[70. 90. 78. 67.]


In [16]:
mean = np.mean(data, axis=1)
print(mean)

[47.   71.   42.5  42.25]


In [17]:
#rata-rata
ava = np.average(data,axis=0)
b = np.average(data,axis=1)
print(a)
print(b)

NameError: name 'a' is not defined

In [18]:
asort = np.argsort(data,axis=0)
print(ava)

[46.   54.75 48.25 53.75]


In [19]:
asa = np.count_nonzero(data,axis=0)
print(asa)

[4 4 4 4]


In [20]:
kal0 = np.sum(data,axis=0)
kal1 = np.sum(data,axis=1)
print(kal0)
print(kal1)

[184. 219. 193. 215.]
[188. 284. 170. 169.]


In [21]:
[y,x] = data.shape
data [2:y,3:y]

array([[78.],
       [67.]])

In [22]:
#delete-arryay
newdata = np.delete(data,[3], axis=1)
newdata

array([[70., 70., 24.],
       [90., 80., 68.],
       [12., 35., 45.],
       [12., 34., 56.]])

In [23]:
np.reshape(data,axis=1)
np.resize(data,axis=1)

TypeError: _reshape_dispatcher() got an unexpected keyword argument 'axis'