In [ ]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

x = [8.0, 1,2,1.5,8, 17]
x_with_nan = [8.0, 1,2, math.nan,1.5,8, 17]

print(x)
print(x_with_nan)

[8.0, 1, 2, 1.5, 8, 17]
[8.0, 1, 2, nan, 1.5, 8, 17]


In [ ]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.   1.5  8.  17. ]
[ 8.   1.   2.   nan  1.5  8.  17. ]
0     8.0
1     1.0
2     2.0
3     NaN
4     1.5
5     8.0
6    17.0
dtype: float64


#mean

In [ ]:
mean_ = sum(x) / len(x)
mean_

6.25

In [ ]:
mean_ = statistics.mean(x)
print(mean_)

6.25


In [ ]:
mean_ = statistics.mean(x_with_nan)
print(mean_)


nan


In [ ]:
mean_ = np.mean(y)
mean_


6.25

In [ ]:
w = [0.7,0.8,0.1,0.2,0.3,0.7]

In [ ]:
wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

7.57142857142857


In [ ]:
wmean = np.average(y, weights=w)
wmean

7.57142857142857

#hmean


In [ ]:
hmean = len(x) / sum(1 / i for i in x)
hmean

2.423762376237624

In [ ]:
hmean = statistics.harmonic_mean(x)
hmean

2.4237623762376237



#gmean

In [ ]:
geomeanlaptop = math.sqrt(1/20 * 7)
geomeanlaptop2 = math.sqrt(1/12 * 4)
print(geomeanlaptop,geomeanlaptop2)


0.5916079783099616 0.5773502691896257


#median

In [ ]:
mediandata = [0.7,0.8,0.1,0.2,0.3,0.7]
mediandata.sort()
mediandata

[0.1, 0.2, 0.3, 0.7, 0.7, 0.8]

In [ ]:
medstat = statistics.median_low(mediandata)
medstat

0.3

In [ ]:
medstat = statistics.median_high(mediandata)
medstat

0.7

In [ ]:
w = [0.7,0.8,0.1,0.2,0.3,0.7]
n = len(w)
if n % 2:
    median_ = sorted(w)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(w), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])

median_

0.5

#modus

In [ ]:
modusdata = [1,1,1,3,4,5,6,7,8,9,1]
modus = max(((modusdata.count(item),item) for item in set (modusdata)))[1]
modus

1

In [ ]:
modusstat = statistics.mode(modusdata)
modusstat

1

#variance


In [ ]:
varstate = statistics.variance(modusdata)
mean_ = sum(modusdata) / len(modusdata)

var_ = sum((item - mean_)**2 for item in modusdata)/(len(modusdata) -1)
print(var_,varstate)

9.163636363636362 9.163636363636364


In [ ]:
stdvq = math.sqrt(var_)
stdvstate =  statistics.stdev(modusdata)
print(stdvq,stdvstate)

3.027149874657078 3.027149874657078


#Skewness

In [ ]:
Skewnes = scipy.stats.skew(modusdata)
Skewnes

0.24935156205469858

#Percentiles

In [ ]:
modusdata

[1, 1, 1, 3, 4, 5, 6, 7, 8, 9, 1]

In [ ]:
FivePercentiles = np.percentile(modusdata,50)
FivePercentiles

4.0

#range

In [ ]:
datarange = max(modusdata) - min(modusdata)
datarange

8

In [ ]:
describedata = scipy.stats.describe(modusdata)
describedata

DescribeResult(nobs=11, minmax=(1, 9), mean=4.181818181818182, variance=9.163636363636364, skewness=0.24935156205469858, kurtosis=-1.3784722222222225)

In [ ]:
x = np.array(range(0,10))
y = np.random.rand(10)
print(x,y)

[0 1 2 3 4 5 6 7 8 9] [0.86380464 0.1147872  0.34527371 0.58716879 0.48947516 0.20526173
 0.63573999 0.49820196 0.51899699 0.96940018]


In [ ]:
civarianxy =np.cov(x,y)
civarianxy


array([[9.16666667, 0.2447761 ],
       [0.2447761 , 0.07035392]])

#2D data

In [ ]:
twod = np.array(
    [[1, 1, 1],
     [1, 2, 4],
     [4, 9, 2],
     [8, 27, 4]])
twod

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 4,  9,  2],
       [ 8, 27,  4]])

In [ ]:
np.mean(twod)

5.333333333333333

In [ ]:
np.median(twod)

3.0

In [ ]:
xmed = np.mean(twod , axis=0)
ymed = np.mean(twod , axis=1)
print(xmed,ymed)

[3.5  9.75 2.75] [ 1.          2.33333333  5.         13.        ]


In [ ]:
scipy.stats.gmean(twod)

array([2.37841423, 4.69525374, 2.37841423])

In [ ]:
scipy.stats.gmean(twod, axis=1)

array([1.        , 2.        , 4.16016765, 9.52440631])

In [ ]:
scipy.stats.describe(twod)

DescribeResult(nobs=4, minmax=(array([1, 1, 1]), array([ 8, 27,  4])), mean=array([3.5 , 9.75, 2.75]), variance=array([ 11.        , 144.91666667,   2.25      ]), skewness=array([ 0.63300966,  0.88189796, -0.21383343]), kurtosis=array([-1.20661157, -0.92573214, -1.72016461]))

In [ ]:
scipy.stats.describe(twod,axis=1)

DescribeResult(nobs=3, minmax=(array([1, 1, 2, 4]), array([ 1,  4,  9, 27])), mean=array([ 1.        ,  2.33333333,  5.        , 13.        ]), variance=array([  0.        ,   2.33333333,  13.        , 151.        ]), skewness=array([0.        , 0.38180177, 0.47033046, 0.62375209]), kurtosis=array([-3. , -1.5, -1.5, -1.5]))

#dataframe

In [ ]:
row_names = [1,2,3,4]
col_names = ["a","b","c"]
df = pd.DataFrame(twod, index=row_names, columns=col_names)
df

a   b  c
1  1   1  1
2  1   2  4
3  4   9  2
4  8  27  4

In [ ]:
df.var()

a     11.000000
b    144.916667
c      2.250000
dtype: float64

In [ ]:
df.mean(axis=1)

1     1.000000
2     2.333333
3     5.000000
4    13.000000
dtype: float64

In [ ]:
df['a']

1    1
2    1
3    4
4    8
Name: a, dtype: int64

In [ ]:
df['a'].mean()

3.5

In [ ]:
df.describe()

a          b     c
count  4.000000   4.000000  4.00
mean   3.500000   9.750000  2.75
std    3.316625  12.038134  1.50
min    1.000000   1.000000  1.00
25%    1.000000   1.750000  1.75
50%    2.500000   5.500000  3.00
75%    5.000000  13.500000  4.00
max    8.000000  27.000000  4.00